version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: go-ekyc-psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ekyc_db
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: go-ekyc-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"    
      - "9001:9001"      
    command: server /data
    volumes:
      - minio_data:/data 
  redis:
    image: redis:latest
    container_name: go-ekyc-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data

volumes:
  psql_data:
  minio_data:
  redis_data:
  rabbitmq_data:
  