FROM golang:1.23.2-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o bin/go-ekyc cmd/app/main.go


FROM alpine
WORKDIR /app
COPY --from=builder /app/bin/go-ekyc /app/go-ekyc
# COPY --from=builder /app/.env /app/.env
EXPOSE 8080
ENTRYPOINT ["/app/go-ekyc"]