ALTER TABLE face_match
ADD COLUMN job_id VARCHAR(100),
ADD COLUMN status VARCHAR(10),
ADD COLUMN completion_at TIMESTAMP;

ALTER TABLE ocr
ADD COLUMN job_id VARCHAR(100),
ADD COLUMN status VARCHAR(10),
ADD COLUMN completion_at TIMESTAMP;