name: ci

on:
  push:
    branches: 
      - '**'
    paths:
      - '**/*.go'
      - Dockerfile_*
      - Makefile  
      - .github/workflows/ci.yml
  pull_request:
    branches: 
      - '**'
    paths:
      - '**/*.go'
      - Dockerfile_*
      - Makefile
      - .github/workflows/ci.yml

jobs:
  lint-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build App
      run: make build-app

    - name: Build Migrate
      run: make build-migrate
    
    - name: Build Cronjob
      run: make build-cronjob

    - name: Build Worker
      run: make build-worker

    - name: Lint
      run: make lint

    - name: Unit Test
      run: make test-unit

    - name: Integration Test
      run: make test-integration

  build-and-push:
    needs: lint-build-and-test
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    env:
      ENV_FILE: .docker-compose.env
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      MINIO_USER: ${{secrets.MINIO_USER}}
      MINIO_PASSWORD: ${{secrets.MINIO_PASSWORD}}
      DOCKERHUB_USERNAME: ${{vars.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}

    steps:
    - uses: actions/checkout@v4 

    - name: Generate Calendar Version
      id: calver
      run: |
        DATE=$(date +'%Y.%m.%d')
        COMMIT=$(git rev-parse --short HEAD)
        echo "DOCKER_IMAGE_TAG=$DATE-$COMMIT" >> $GITHUB_ENV
      env:
        TZ: Asia/Kolkata

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile_app
        push: true
        tags: justsushant/go-ekyc:app-${{ env.DOCKER_IMAGE_TAG }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile_cronjob
        push: true
        tags: justsushant/go-ekyc:cronjob-${{ env.DOCKER_IMAGE_TAG }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile_worker
        push: true
        tags: justsushant/go-ekyc:worker-${{ env.DOCKER_IMAGE_TAG }}